version: '3'
services:
  dockerhub:
    image: maccyber/micro-dockerhub-hook
    # build: .
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./scripts:/src/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      # Path to docker-compose files who are triggered by scripts:
      # - /srv:/srv
